#!/usr/bin/env bash
set -e

if command -v systemctl >/dev/null 2>&1; then
  systemctl stop pervasivecx-core.service || true
  systemctl stop pervasivecx-collector.service || true
  systemctl disable pervasivecx-core.service || true
  systemctl disable pervasivecx-collector.service || true
fi
